// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKDsrvgIzGEX565ALJ1vbKudQ2ELrTEzw',
    appId: '1:177189268795:android:faba118e0e81fefe0a1b1e',
    messagingSenderId: '177189268795',
    projectId: 'getnapp',
    databaseURL: 'https://getnapp-default-rtdb.firebaseio.com',
    storageBucket: 'getnapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnJL8L9yqHUb__b-o5e-0t-3gzyZN6T1I',
    appId: '1:177189268795:ios:7d65df62934b36e80a1b1e',
    messagingSenderId: '177189268795',
    projectId: 'getnapp',
    databaseURL: 'https://getnapp-default-rtdb.firebaseio.com',
    storageBucket: 'getnapp.appspot.com',
    iosClientId: '177189268795-mk8109mvgjnm915412r8fdnfdjdgh3ag.apps.googleusercontent.com',
    iosBundleId: 'com.getn.driver.getnDriver',
  );
}
